services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  beardw/test_various_env:b943529
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G  
    platform: linux/amd64
