# name: wine-classifier-env
# channels:
#   - conda-forge
#   #- defaults
# dependencies:
#   - python=3.11
#   - numpy=2.3.5
#   - pandas=2.3.3
#   - scikit-learn=1.7.2
#   - matplotlib=3.10.8
#   #- ipykernel=7.1.0
#   #- ipython=9.7.0
#   #- nb_conda_kernels=2.5.1
#   - requests=2.32.5
#   - altair=5.5.0
#   - pandera=0.26.1
#   - deepchecks=0.3.2
#   #- vegafusion=2.0.2 #added
#   #- vegafusion-jupyter=1.6.9 #added
#   #- vegafusion-python-embed=1.6.9 #added
#   - vl-convert-python=1.8.0 #added
#   - pyarrow=21.0.0 #added
#   #- vega_datasets=0.9.0
#   #- jinja2=3.1.6
#   #- graphviz=13.1.2
#   #- python-graphviz=0.21
#   #- plotly=6.4.0
#   #- panel=1.8.3
#   #- autograd=1.8.0
#   #- lightgbm=4.6.0
#   #- watchfiles=1.1.1
#   #- pip=25.3

# this runs but then no matplot and requests doesn't work
# name: wine-classifier-env
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - altair=5.1.2
#   - pandas=2.1.2
#   - pandera=0.20.4
#   - python=3.11
#   - scikit-learn=1.3.2
#   - vegafusion=1.4.3
#   - vegafusion-jupyter=1.4.3
#   - vegafusion-python-embed=1.4.3
#   - vl-convert-python=1.0.1
#   - requests=2.31.0 #2.31.0 #2.32.5
#   - click=8.1.7
#   - tabulate=0.9.0
#   - quarto=1.5.57
#   - make=4.4.1
#   - pytest=8.3.4
#   - responses=0.24.1
#   #- matplotlib=3.10.8
#   #- deepchecks=0.3.2

name: wine-classifier-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.3.5
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - ipykernel=7.1.0
  - ipython=9.7.0
  - nb_conda_kernels=2.5.1
  - jinja2=3.1.6
  - requests=2.32.5
  - graphviz=13.1.2
  - python-graphviz=0.21
  - plotly=6.4.0
  - panel=1.8.3
  - vega_datasets=0.9.0
  - altair-all=5.5.0
  - autograd=1.8.0
  - lightgbm=4.6.0
  - watchfiles=1.1.1
  - pip=25.3
  - pandera=0.26.1
  - pip:
    - deepchecks==0.19.1