name: wine-classifier-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.3.5
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - ipykernel=7.1.0
  - ipython=9.7.0
  #- nb_conda_kernels=2.5.1
  - requests=2.32.5
  - altair=5.5.0
  - pandera=0.26.1
  - deepchecks=0.3.2
  - vegafusion=2.0.2 #added
  - vegafusion-jupyter=1.6.9 #added
  - vegafusion-python-embed=1.6.9 #added
  - vl-convert-python=1.8.0 #added
  - pyarrow=21.0.0 #added
  #- vega_datasets=0.9.0
  #- jinja2=3.1.6
  #- graphviz=13.1.2
  #- python-graphviz=0.21
  #- plotly=6.4.0
  #- panel=1.8.3
  #- autograd=1.8.0
  #- lightgbm=4.6.0
  #- watchfiles=1.1.1
  #- pip=25.3