name: wine-classifier-env
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- numpy=2.3.5
- pandas=2.3.3
- scikit-learn=1.7.2
- matplotlib=3.9
- ipykernel # =7.1.0
- ipython # =9.7.0
- requests=2.32.5
- graphviz=13.1.2
- python-graphviz=0.21
- plotly=6.4.0
- vega_datasets=0.9.0
- altair-all=5.5.0
- pip=25.3
- pandera=0.26.1
- click=8.1.7
- tabulate=0.9.0
- quarto=1.5.57
- make=4.4.1
# - watchfiles=1.1.1
# - lightgbm=4.6.0
# - autograd=1.8.0
# - panel=1.8.3
# - jinja2=3.1.6